services:
  mistserver:
    container_name: mistserver
    image: ghcr.io/r0gger/mistserver:latest
    pull_policy: always
    restart: unless-stopped
    volumes:
      - /path-to/config:/config
      - /path-to/media:/media
    network_mode: host
    shm_size: 2048m 
